include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.graphql.dart"
    - "**/*.pb.dart"
    - "**/*.pbenum.dart"
    - "**/*.pbjson.dart"
    - "**/*.pbgrpc.dart"
    - test/.test_coverage.dart
    - lib/generated_plugin_registrant.dart
    - lib/firebase_options.dart

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    #recommend to ignore by freezed package author:
    #https://github.com/rrousselGit/freezed/issues/488#issuecomment-894358980
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    use_setters_to_change_properties: ignore

  plugins:

linter:
  rules:

# Learn more: https://dcm.dev/docs/individuals/configuration
dart_code_metrics:
  extends:
    - recommended
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.graphql.dart"
    - "**/*.pb.dart"
    - "**/*.pbenum.dart"
    - "**/*.pbjson.dart"
    - "**/*.pbgrpc.dart"
    - test/.test_coverage.dart
    - lib/generated_plugin_registrant.dart
    - lib/firebase_options.dart

  rules:
