name: retro_logger
description: "A simple Logger that does not have any dependencies and is easy to use."
version: 0.0.11
homepage: https://retro-logger.web.app/
repository: https://github.com/callmephil/retro_logger
issue_tracker: https://github.com/callmephil/retro_logger/issues

environment:
  sdk: ^3.13.2
  flutter: ^3.47.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart: any

  material_ui: ^1.1.0
  cupertino_ui: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
