name: retro_logger
description: "A simple Logger that does not have any dependencies and is easy to use."
version: 0.0.8
homepage: https://retro-logger.web.app/
repository: https://github.com/callmephil/retro_logger
issue_tracker: https://github.com/callmephil/retro_logger/issues

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
